version: "3.8"

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=most-secret-password-change-me
      - POSTGRES_DB=mattermost
      - TZ=UTC
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  mattermost:
    image: mattermost/mattermost-team-edition:9.5.2
    depends_on:
      - db
    environment:
      - TZ=UTC
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:most-secret-password-change-me@db:5432/mattermost?sslmode=disable&connect_timeout=10
      - MM_SERVICESETTINGS_SITEURL=http://192.168.1.154:31201
      - MM_BLEVESETTINGS_INDEXDIR=/mattermost/bleve-indexes
    ports:
      - target: 8065
        published: 31201
        protocol: tcp
        mode: ingress
    volumes:
      - ./volumes/app/config:/mattermost/config:rw
      - ./volumes/app/data:/mattermost/data:rw
      - ./volumes/app/logs:/mattermost/logs:rw
      - ./volumes/app/plugins:/mattermost/plugins:rw
      - ./volumes/app/client/plugins:/mattermost/client/plugins:rw
      - ./volumes/app/bleve-indexes:/mattermost/bleve-indexes:rw
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  coturn:
    image: coturn/coturn:latest
    environment:
      - TZ=UTC
    command:
      - -n
      - --log-file=stdout
      - --lt-cred-mech
      - --fingerprint
      - --no-stdout-log
      - --listening-port=3478
      - --min-port=31202
      - --max-port=31206
      - --realm=192.168.1.154
      - --user=mmuser:mmuser_turn_password_change_me
      - --external-ip=192.168.1.154
    ports:
      # STUN/TURN Ports in host mode for media traffic efficiency (Manual individual listing for swarm)
      - target: 3478
        published: 3478
        protocol: tcp
        mode: host
      - target: 3478
        published: 3478
        protocol: udp
        mode: host
      # Relay port range (must be host mode and individual for Swarm)
      - target: 31202
        published: 31202
        protocol: udp
        mode: host
      - target: 31203
        published: 31203
        protocol: udp
        mode: host
      - target: 31204
        published: 31204
        protocol: udp
        mode: host
      - target: 31205
        published: 31205
        protocol: udp
        mode: host
      - target: 31206
        published: 31206
        protocol: udp
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
