# CoTURN Configuration for Mattermost Swarm
listening-port=3478
fingerprint
lt-cred-mech
user=mmuser:mmuser_turn_password_change_me
realm=192.168.1.154
log-file=stdout
no-stdout-log
external-ip=192.168.1.154
listening-ip=0.0.0.0
min-port=31202
max-port=31206
verbose
